### ISSUE TITLE
str_replace

### ISSUE THREAD

**Issue by trdwll** [Laim/TrueAchievementsScraper#1]
Instead of forcing users to add **+** to the gamertag, just use _str_replace_ to replace spaces with a **+**.

Reference:
http://php.net/manual/en/function.str-replace.php

**Comment by Laim** [comment]
Will add this when I get the chance.

**Comment by Laim** [comment]
Decided to use preg_replace instead of str_replace, but this issue is finally resolved - after nearly a year.
